variable "node_name_prefix" {
  type        = string
  description = "Prefix used for all node names"
}

variable "ami_id" {
  type        = string
  description = "AMI to use for all nodes"
}

variable "instance_type" {
  type        = string
  description = "Instance type to use for all nodes"
}

variable "key_name" {
  type        = string
  description = "Name of SSH key pair to attach to all nodes"
}

variable "subnet_id" {
  type        = string
  description = "ID of subnet to attach to all nodes"
}

variable "aio_security_group_id" {
  type        = string
  description = "Security group to attach to all-in-one nodes"
}

variable "worker_security_group_id" {
  type        = string
  description = "Security group to attach to worker nodes"
}

variable "registration_command" {
  type        = string
  description = "Command generated by Rancher to join a node to a Custom cluster"
}

variable "os_username" {
  type        = string
  description = "Username to add to the docker group when installing Docker"
}

variable "aio_count" {
  type        = number
  description = "Number of all-in-one (all roles) to provision"
  default     = 1
}

variable "worker_count" {
  type        = number
  description = "Number of worker nodes to provision"
  default     = 2
}

variable "use_all_ips" {
  type        = bool
  description = "Use both public and private IPs in the RKE cluster config"
  default     = false
}

variable "root_disk_size" {
  type        = number
  description = "Size of root disk for all created instances"
  default     = 100
}

variable "extra_tags" {
  type        = map(string)
  description = "Extra tags to apply to created instances"
  default     = {}
}
